// Generated by CoffeeScript 1.6.3
(function() {
  var editorInit, exampleInit, main, updateTokens;

  editorInit = function() {
    var Range, editor, ff, prog, session;
    Range = ace.require("ace/range").Range;
    editor = ace.edit("editor");
    xlang.editor = editor;
    session = editor.getSession();
    editor.setTheme("ace/theme/tomorrow");
    session.setMode("ace/mode/golang");
    editor.renderer.setShowGutter(false);
    editor.setHighlightActiveLine(false);
    editor.setShowFoldWidgets(false);
    editor.setDisplayIndentGuides(false);
    ff = "Consolas, Inconsolata, Monaco, \"Courier New\", Courier, monospace";
    editor.setOptions({
      maxLines: Infinity,
      minLines: 10,
      fontFamily: ff,
      fontSize: "13px"
    });
    editor.commands.removeCommands(["gotoline", "find"]);
    prog = ['var x = 3', 'var y = 4', '', 'func main() {', '\tprintln(x + y)', '}'].join('\n');
    editor.setValue(prog);
    editor.clearSelection();
  };

  exampleInit = function() {
    var examples, f, li, ul, _i, _len;
    examples = ['3p4'];
    ul = $('<ul id="examples"/>');
    for (_i = 0, _len = examples.length; _i < _len; _i++) {
      f = examples[_i];
      li = $('<li><a href="#">' + f + '</a></li>');
      li.find('a').click(function(e) {
        e.preventDefault();
        $.ajax("tests/" + f + ".x", {
          success: function(dat) {
            xlang.editor.setValue(dat);
            xlang.editor.clearSelection();
          }
        });
      });
      ul.append(li);
    }
    $("div#filelist").append(ul);
  };

  updateTokens = function() {
    var code, parsed, tokens;
    code = xlang.editor.getValue();
    tokens = xlang.parseTokens("", code);
    $("#tokens").html(tokens);
    parsed = xlang.parse("test.x", code);
    $("#console").html(parsed.errs);
    $("#stmt-tree").html(parsed.block);
  };

  main = function() {
    editorInit();
    exampleInit();
    updateTokens();
    xlang.editor.getSession().on("change", function() {
      updateTokens();
    });
  };

  $(document).ready(main);

}).call(this);

/*
//@ sourceMappingURL=playg.map
*/
